#pragma once

#define STEAL_CHANCE_LOCATION 0x78b830
#define STEAL_CHANCE_ORIGINAL_0 0x0f
#define STEAL_CHANCE_ORIGINAL_1 0xb6
#define STEAL_CHANCE_ORIGINAL_2 0x5e
#define STEAL_CHANCE_ORIGINAL_3 0x0a
#define STEAL_CHANCE_NEW_0 0x66
#define STEAL_CHANCE_NEW_1 0xbb
#define STEAL_CHANCE_NEW_2 0xff
#define STEAL_CHANCE_NEW_3 0x00

#define RARE_STEAL_CHANCE_LOCATION 0x78b905
#define RARE_STEAL_CHANCE_ORIGINAL_0 0x3b
#define RARE_STEAL_CHANCE_ORIGINAL_1 0x45
#define RARE_STEAL_CHANCE_ORIGINAL_2 0x10
#define RARE_STEAL_CHANCE_NEW_0 0x83
#define RARE_STEAL_CHANCE_NEW_1 0xf8
#define RARE_STEAL_CHANCE_NEW_2 0x7f
